### PR TITLE
test: use ISO strings for dates

### PR DESCRIPTION
**Pull request by targos**
Fixes the tests for Node 8.
Ref: https://github.com/nodejs/citgm/issues/466

### CODE REVIEW

**Comment by gibfahn** [comment]
@targos to confirm, this still works with older node versions right?

**Comment by targos** [comment]
I confirm. Just ran the tests on 0.8, 0.10, 0.12, 4, 6 and 8 ;)

**Comment by targos** [comment]
ping @mscdex. Could you please check this?

**Comment by MylesBorins** [comment]
Still seeing failurs on 8.x

ping @mscdex

**Comment by targos** [comment]
ping

**Comment by al-k21** [comment]
Seems like this resolves the issue.
Why this has not landed? @targos  @mscdex
 
Can we land this and then we can unskip ftp.

**Comment by targos** [comment]
I didn't get any answer, so I closed this during a personal PR cleanup.
Happy to reopen if it can be merged and released by someone.

**Pull request closed without merging**
